export class EndPoints {
  public static SIGN = 'auth/sign/'
  public static LOGIN = 'auth/log/'
  public static USER_EXIST = 'user/exist/'
  public static AGENCY_ADD = 'agency/add/'
  public static AGENCY_GET = 'agency/get/'
  public static AGENCY_UPDATE = 'agency/update/'
  public static AGENCY_DELETE = 'agency/delete/'
  public static COMPANY_ADD = 'company/add/'
  public static COMPANY_GET = 'company/get/'
  public static COMPANY_UPDATE = 'company/update/'
  public static COMPANY_DELETE = 'company/delete/'
  public static COMPANY_BY_AGENCY = 'company/by-agency/'
  public static VEHICLE_ADD = 'vehicle/add/'
  public static VEHICLE_GET = 'vehicle/get/'
  public static VEHICLE_UPDATE = 'vehicle/update/'
  public static VEHICLE_DELETE = 'vehicle/delete/'
  public static VEHICLE_BY_COMPANY = 'vehicle/by-company/'
  public static PRICING_ADD = 'pricing/add/'
  public static PRICING_GET = 'pricing/get/'
  public static PRICING_UPDATE = 'pricing/update/'
  public static PRICING_DELETE = 'pricing/delete/'
}
